### ISSUE TITLE
Pending incorrectly takes precedence over "save as draft"

### ISSUE THREAD

**Issue by UaMV** [codebykat/wp-post-by-email#24]
Security options for incoming posts allow the ability to 'Save as drafts'. However, incoming posts are saved as pending posts. These options should be corrected either by listing 'Save as pending', changing wp_insert_post post_status argument to draft, or by allowing both statuses as an option.

**Comment by codebykat** [comment]
Fixed (in a roundabout way) in https://github.com/codebykat/wp-post-by-email/commit/601ff4dcf24c4bf819453eab560caedb8801fc0f.

Changed the status to "draft" to match the labeling on the options. The name of the option is still misleading, but I can't be bothered to deal with the backwards-incompatiblity of changing it right now.
