### ISSUE TITLE
Post by email throws exception when imap is used.

### ISSUE THREAD

**Issue by chfw** [codebykat/wp-post-by-email#27]
Hi all:

Wordpress was used to create two sites (A, B) and both uses post-by-email. Site A is free for anyone to read; Site B is restricted for subscribed users via Active Directory. Now, post by email via site A works while post to site B does not work. Not working means the post stays in the email box and never gets published. 

I attempted to click "Check now" button on site B and got these error logs:
1. PHP Catchable fatal error:  Argument 3 passed to Horde_Imap_Client_Exception_ServerResponse::__construct() must be an instance of Horde_Imap_Client_Interaction_Server, integer given, called in /var/www/html/wp-content/plugins/post-by-email/include/Horde/Imap/Client/Socket.php on line 3946 and defined in /var/www/html/wp-content/plugins/post-by-email/include/Horde/Imap/Client/Exception/ServerResponse.php on line 55, referer: http://....

on Site A, I don't get any error logs. 

Any suggestion on how to debug this?

**Comment by codebykat** [comment]
Thanks - this is probably a PHP version problem. What are the PHP versions of the two different sites?

**Comment by codebykat** [comment]
(BTW, the error not being reported is likely the fault of your WordPress or PHP config. In general, errors are suppressed unless WP_DEBUG is enabled. I don't necessarily agree with that, as it tends to result in the confusing "white screen of death", which as you noted is not very user-friendly... but that's how WP is set up.)

**Comment by chfw** [comment]
I am sorry that I have moved on from the issue. Thanks for your attention and time.
