### ISSUE TITLE
An error occurred: POP3 server denied authentication.

### ISSUE THREAD

**Issue by spagu** [codebykat/wp-post-by-email#40]
I have a problem with a plugin for a while. Using google apps to download mails - this was working for a while but now it seems to stop. 
-Ports 995 and 993 are enabled (tested)
-PHP 5.6
-Google POP and IMAP enabled
-http://www.google.com/accounts/DisplayUnlockCaptcha  tried this but does not help
-upgraded manually horde to the latest version (did not help)
-Debug gives nothing or I do not know how to do it. 

Any ideas? Clues where to look for a problem ?

**Comment by spagu** [comment]
OK I think it is solved now. Please take a look on this:
https://support.google.com/accounts/answer/6010255

"Allow access for less secure apps"  must be ON for an google apps account
https://myaccount.google.com/security?utm_source=OGB&pli=1#signin  ( very bottom of the page )

**Comment by spagu** [comment]
OK I think it is solved now. Please take a look on this:
https://support.google.com/accounts/answer/6010255

"Allow access for less secure apps"  must be ON for an google apps account
https://myaccount.google.com/security?utm_source=OGB&pli=1#signin  ( very bottom of the page )

**Comment by codebykat** [comment]
Thanks @spagu! I will add that to the README.
